import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import CountdownTimer from '@/components/landing/SectionComponents/CountdownTimer';
import TierBadge from '@/components/landing/SectionComponents/TierBadge';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Clock, Users } from 'lucide-react';
const ProductCard = (props) => {
    const { imageUrl, title, status, startsIn, duration, expectedUsers, productCount, seller } = props.item;
    return (_jsx("div", { children: _jsxs(Card, { className: "overflow-hidden bg-white border-gray-200 shadow-sm hover:shadow-md transition-shadow py-0", children: [_jsxs("div", { className: "relative w-full overflow-hidden h-56", children: [_jsx("img", { src: imageUrl || "/placeholder.svg", alt: title, className: "object-cover" }), _jsx(Badge, { className: `absolute top-3 left-3 ${status === "live" ? "bg-red-500 hover:bg-red-600 text-white" : "bg-gray-100 hover:bg-gray-200 text-gray-800"}`, children: status === "live" ? "Live" : "Upcoming" })] }), _jsxs(CardContent, { className: "p-4 pt-0 space-y-4", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 line-clamp-2", children: title }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs(Avatar, { className: "h-8 w-8", children: [_jsx(AvatarImage, { src: seller.avatar || "/placeholder.svg", alt: seller.name }), _jsx(AvatarFallback, { children: seller.name.charAt(0) })] }), _jsx("span", { className: "text-sm font-medium text-gray-700", children: seller.name }), _jsx(TierBadge, { tier: seller.tier })] }), _jsxs("div", { className: "flex items-center justify-between text-sm text-gray-600", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "h-4 w-4" }), _jsxs("span", { children: ["Starts in ", startsIn, " hours"] })] }), _jsxs("span", { children: [duration, " min"] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm text-gray-600", children: [_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Users, { className: "h-4 w-4" }), _jsxs("span", { children: [expectedUsers, " expected"] })] }), _jsxs("span", { children: [productCount, " products"] })] }), status === "live" ? (_jsx(Button, { className: "w-full bg-accent hover:bg-accent text-white font-medium rounded-full", children: "Join Live Sale Stream" })) : (_jsxs(Button, { variant: "outline", className: "w-full text-accent border-gray-300 hover:bg-accent bg-transparent rounded-full", children: ["Wait More ", _jsx(CountdownTimer, { targetHours: startsIn })] }))] })] }) }));
};
export default ProductCard;
